export default (sequelize, Sequelize) => {

    const FlashCard = sequelize.define("flashcard", 
        {
            _id: {
                type: Sequelize.UUID,
                defaultValue: Sequelize.UUIDV4
            },
            question: {
                type: Sequelize.STRING,
                allowNull: false
            },
            answer: {   // may be generated by AI or not
                type: Sequelize.STRING
            },
            chat_thread: {
                type: Sequelize.STRING,
                allowNull: true
            },
            completed: {
                type: Sequelize.BOOLEAN,
                defaultValue: false
            },
            user_id: {  // User the flashcard is associated to
                type: Sequelize.INTEGER,
                references: {
                    model: User,
                    key: '_id',
                }
            },
        },
        {
            timestamps: true   // Includes createdAt and updatedAt
        }
)

    const FlashCardType = {
        type: {
            type: Sequelize.opt
            
        }
    }

    return FlashCard
} 
